### ISSUE TITLE
Conversion to string failed - and a couple of additional observation.

### ISSUE THREAD

**Issue by Ale-Rossi** [gbouras13/pharokka#122]
* phrokka version: 0.1.1
* Python version: 3.9.13
* Operating System: Ubuntu 18.04 LTS Server

### Description

I launched pharokka on my viral contigs to annotate them.

### What I Did

```
$ pharokka.py -i "$infile" -d /data/db/PHROGS -t 60

FASTA checked
Beginning Phanotate
Traceback (most recent call last):
  File "/home/bioinfo/anaconda3/envs/pharokka/bin/pharokka.py", line 16, in <module>
    processes.translate_fastas(out_dir)
  File "/home/bioinfo/anaconda3/envs/pharokka/bin/modules/processes.py", line 58, in translate_fastas
    dna_description =   phan_df['start'].iloc[i].astype(str) + "_" + phan_df['stop'].iloc[i].astype(str)
AttributeError: 'str' object has no attribute 'astype'
```

That's it. .astype() is an attribute of pandas objects, such as dataframes. I suggest using the str() function instead
```
str(phan_df['start'].iloc[i]) + "_" + str(phan_df['stop'].iloc[i])
```

That would solve the issue.

I've also noticed that the values in the columns `start` and `stop` are already strings, but I suspect this is actually undesired and has to do with the fact that there are comment rows included in the database. Here's a snapshot of my `cleaned_phanotate.tsv` file:

```
start   stop    frame   contig  score   gene
648     85      -       627_AS_032deLWdelim     -5950.328915480545228412878818  627_AS_032deLWdelim0 648_85
827     645     -       627_AS_032deLWdelim     -19.03537314250255055372969411  627_AS_032deLWdelim1 827_645
1027    824     -       627_AS_032deLWdelim     -7.209186680523061904788001127  627_AS_032deLWdelim2 1027_824
1242    1027    -       627_AS_032deLWdelim     -51.69015098948056216884224348  627_AS_032deLWdelim3 1242_1027
1418    1224    -       627_AS_032deLWdelim     -15.61481905040385983902763601  627_AS_032deLWdelim4 1418_1224
2251    1409    -       627_AS_032deLWdelim     -138334.0158863974592453390774  627_AS_032deLWdelim5 2251_1409
3306    2257    -       627_AS_032deLWdelim     -16974294.17134049948965038800  627_AS_032deLWdelim6 3306_2257
4066    3335    -       627_AS_032deLWdelim     -41290.30362059099239253731847  627_AS_032deLWdelim7 4066_3335
4171    4079    -       627_AS_032deLWdelim     -0.05403914249865158487576726233        627_AS_032deLWdelim8 4171_4079
4365    4180    -       627_AS_032deLWdelim     -11.59954147505824609448388817  627_AS_032deLWdelim9 4365_4180
5054    4368    -       627_AS_032deLWdelim     -50964.95419646835233135824328  627_AS_032deLWdelim10 5054_4368
4988    5545    +       627_AS_032deLWdelim     -207.1401271894045440866113863  627_AS_032deLWdelim11 4988_5545
5549    5659    +       627_AS_032deLWdelim     -0.1655476160158931084311159951 627_AS_032deLWdelim12 5549_5659
5831    6166    +       627_AS_032deLWdelim     -96.74353881729221545778586926  627_AS_032deLWdelim13 5831_6166
6166    7065    +       627_AS_032deLWdelim     -1311690.688900922166701121237  627_AS_032deLWdelim14 6166_7065
7109    7327    +       627_AS_032deLWdelim     -154.4648528527137585470452864  627_AS_032deLWdelim15 7109_7327
7351    7455    +       627_AS_032deLWdelim     -0.06459941106751764040614335289        627_AS_032deLWdelim16 7351_7455
7452    7628    +       627_AS_032deLWdelim     -1.751788612773718521814506920  627_AS_032deLWdelim17 7452_7628
7920    7795    -       627_AS_032deLWdelim     -1.899751346464667351966481006  627_AS_032deLWdelim18 7920_7795
#id:    1200_AS_032deLWdelim       
#START  STOP    FRAME   CONTIG  SCORE   CONTIG20 #START_STOP
92      3       -       1200_AS_032deLWdelim    -0.3947089479339262925811772674 1200_AS_032deLWdelim21 92_3
397     104     -       1200_AS_032deLWdelim    -203.0864784150881507217786563  1200_AS_032deLWdelim22 397_104
```

The lines `#id:    1200_AS_032deLWdelim` and `#START  STOP    FRAME   CONTIG  SCORE   CONTIG20 #START_STOP` are maybe out of place.

Also, are you sure the delimiter (file `bin/modules/processes.py`, function `add_delim_trim_fasta`, line 27) is actually the string `"delim"`?
It looks a bit weird to me, but maybe it's a design feature.

Cheers! Cannot wait to look at its results.

**Comment by gbouras13** [comment]
Hi Ale-Rossi,

Thanks for using pharokka and thank you for your suggestions, I will be implementing these fixes shortly. If you have any other output suggestions or requests let me know.

Regarding cleaned_phanotate.tsv, this is a temporary file that is removed from the final output when pharokka runs successfully.

And with the delimiter, it is intended for now - I plan to change it in the future but it is removed before the output files.

George

**Comment by gbouras13** [comment]
Have update Bioconda with the latest fixes Ale-Rossi, if you have any other issues please let me know.
