### ISSUE TITLE
Add validation if out directory exists

### ISSUE THREAD

**Issue by gbouras13** [gbouras13/pharokka#271]
* phrokka version: v1.3.2

The error is pretty good but add explicit check

```
Traceback (most recent call last):
  File "~pharokka.py", line 57, in <module>
    out_dir = input_commands.instantiate_dirs(args.outdir, args.meta, args.force)
  File "~/pharokka/bin/input_commands.py", line 53, in instantiate_dirs
    os.mkdir(output_dir)
FileExistsError: [Errno 17] File exists: 'NC_007458.fasta'
```

**Comment by gbouras13** [comment]
Fixed by #275
