### ISSUE TITLE
Prodigal not working Pharokka v1.4.1

### ISSUE THREAD

**Issue by raw-lab** [gbouras13/pharokka#314]
* pharokka version: 1.4.1
* Python version: 3.10
* Operating System: Linux

### Description

2023-12-20 15:18:04.879 | INFO     | input_commands:check_dependencies:529 - Pyrodigal version is v3.0.1
2023-12-20 15:18:04.879 | INFO     | input_commands:check_dependencies:530 - Pyrodigal version is ok.
2023-12-20 15:18:04.883 | INFO     | input_commands:validate_fasta:205 - Checking Input FASTA.
2023-12-20 15:18:04.886 | INFO     | input_commands:validate_fasta:207 - FASTA checked.
2023-12-20 15:18:04.886 | INFO     | input_commands:validate_gene_predictor:216 - Prodigal will be used for gene prediction.
2023-12-20 15:18:04.888 | INFO     | __main__:main:277 - Implementing Prodigal using Pyrodigal.
Traceback (most recent call last):
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 447, in <module>
    main()
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 278, in main
    run_pyrodigal(input_fasta, out_dir, args.meta, args.coding_table)
  File "/home/docwhite/miniconda3/envs/pharokka/bin/processes.py", line 276, in run_pyrodigal
    orf_finder = pyrodigal.OrfFinder(meta=prodigal_metamode)
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'

### What I Did

```
pharokka.py -i LP_CU-CL_31_18.fna -o test -d ~/miniconda3/envs/pharokka/databases/ -t 8 -g prodigal
pharokka.py -i LP_CU-CL_31_18.fna -o test -d ~/miniconda3/envs/pharokka/databases/ -t 8 -g prodigal --fast
```

It can't find pyrodigal.

**Comment by gbouras13** [comment]
Hi @raw-lab ,

This is because pyrodigal v3 is being used with the old Pharokka v1.4.1 version. The most recent version is 1.5.1. 

Pyrodigal updated its API in v3 to `GeneFinder` not `OrfFinder`, breaking this.

Pharokka v1.5 implements a fix for this. 

Therefore, I'd recommend updating pharokka to v1.5.1. 

If you really want to use v1.4.1, please downgrade pyrodigal to v2.

George

**Comment by gbouras13** [comment]
Closing this issue as fix is to upgrade Pharokka
