### ISSUE TITLE
Alphabet error while annotating phage

### ISSUE THREAD

**Issue by Fabian-Bastiaanssen** [gbouras13/pharokka#331]
* pharokka version:1.6.1
* Python version:Python 3.10.8
* Operating System:Ubuntu 22.04.2 LTS

### Description

I was trying to annotate a circular phage with pharokka, the sequence only contains nucleotides and seems to be fine for other tools. I can't see any reasons why this might throw an error.
[sequence_203.txt](https://github.com/gbouras13/pharokka/files/14299262/sequence_203.txt)

### What I Did

pharokka.py -f -i all_fastas/fastas/sequence_203.fasta -o all_fastas/sequence_203 -d /data/san/data0/databases/Pharokka/20230827 -t 4 -g prodigal-gv  --skip_extra_annotations

2024-02-15 15:57:08.713 | INFO     | __main__:main:363 - Running PyHMMER on PHROGs.
Traceback (most recent call last):
  File "/data/san/data1/users/fabian/miniforge/envs/pharokka2/bin/pharokka.py", line 499, in <module>
    main()
  File "/data/san/data1/users/fabian/miniforge/envs/pharokka2/bin/pharokka.py", line 364, in main
    best_results_pyhmmer = run_pyhmmer(
  File "/data/san/data1/users/fabian/miniforge/envs/pharokka2/bin/hmm.py", line 34, in run_pyhmmer
    with pyhmmer.easel.SequenceFile(
  File "pyhmmer/easel.pyx", line 6369, in pyhmmer.easel.SequenceFile.__init__
  File "pyhmmer/easel.pyx", line 6363, in pyhmmer.easel.SequenceFile.__init__
ValueError: Could not determine alphabet of file: 'all_fastas/sequence_203/prodigal-gv_aas_tmp.fasta's

**Comment by gbouras13** [comment]
Hi @Fabian-Bastiaanssen ,

I can reproduce this error.

The reason is because the first CDS is 

```
NDDDDDNDDDDNDDDDNDDDDNDND*
```

which is so repetitive/not-diverse and means pyhmmer can't infer whether it is a protein or nucleotide I am pretty sure and so crashes.

While I look into fixing the error, you can try one of two couple of things:


1. Reroient your circular phage to begin elsewhere, which should hopefully work when you annotate that with pharokka (e.g. with Dnaapler https://github.com/gbouras13/dnaapler - you can do this by passing `--dnaapler` to pharokka )
2. use `--mmseqs2_only` to disable pyhmmer

George
