### ISSUE TITLE
Error with some sequences

### ISSUE THREAD

**Issue by Sudaraka88** [gbouras13/pharokka#335]
Hey, thanks for writing and maintaining pharokka! Have found it really useful for my work.

This is my setup:
* pharokka version: 1.7.0
* Python version:  3.10.13
* Operating System: Linux

### Description

When I try to run pharokka with the attached sequence, I run to the following error:

Traceback (most recent call last):
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/bin/pharokka.py", line 483, in <module>
    main()
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/bin/pharokka.py", line 405, in main
    pharok.create_gff()
  File "/data/data1/sudarakm/tools/miniconda3/envs/pharokka_env/bin/post_processing.py", line 925, in create_gff
    minced_df.start = minced_df.start.astype(int)
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/generic.py", line 6640, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 430, in astype
    return self.apply(
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 101, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/data1/sudarakm/tools/miniconda3/envs/pharokka_env/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 145, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer[pharokka_test.fa.zip](https://github.com/gbouras13/pharokka/files/14518756/pharokka_test.fa.zip)

I am also attaching the log file which will hopefully help identify the issue
[pharokka_log.txt](https://github.com/gbouras13/pharokka/files/14518789/pharokka_log.txt)

I am able to run phastest on this sequence: https://phastest.ca/submissions/ZZ_bef2b10127
Admittedly this is not a very good phage, but I have run pharokka on a lot of (similar) phages using the exact same setup/command. 

Cheers,
Sudaraka

**Comment by gbouras13** [comment]
Hi @Sudaraka88,

This is a very strange bug. I could not reproduce it (Mac mini M1), pharokka ran fine. I've attached the results.
[sudarka1.7.0.zip](https://github.com/gbouras13/pharokka/files/14519343/sudarka1.7.0.zip)

The issue according to your log appears to be with parsing CRISPR repeats (`minced_df.start = minced_df.start.astype(int)`) - this is a rare phage with one. 

Not really sure why Mac works but not your linux machine. If you run into this error again, try `--skip_extra_annotations` to skip MINCED perhaps.

In any case, if you find pharokka useful, please try out my new program phold https://github.com/gbouras13/phold  - we are finishing benchmarking & I need to formally write up a manuscript, but I have found that it gives (a lot) better results than even pharokka. 

George

**Comment by Sudaraka88** [comment]
Hi George, 

Thanks for testing this out. That is strange indeed!
I'll retry on my Mac as well and report back if it fails...

Thanks for the tip on phold, will check it out. Keep up the good work!
