### ISSUE TITLE
Libgsl error from mash - cant run

### ISSUE THREAD

**Issue by raw937** [gbouras13/pharokka#341]
* pharokka version: 1.7.1
* Python version: Python 3.10.8
* Operating System: Ubuntu 24.04

### Description

Won't run. Had some errors. 

Traceback (most recent call last):
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 489, in <module>
    main()
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 128, in main
    ) = check_dependencies(args.skip_mash)
  File "/home/docwhite/miniconda3/envs/pharokka/bin/input_commands.py", line 540, in check_dependencies
    mash_major_version = int(mash_out.split(".")[0])
ValueError: invalid literal for int() with base 10: 'mash: error while loading shared libraries: libgsl'

### Command
```
pharokka.py -i phageX.fna -d ~/miniconda3/envs/pharokka/databases/ -t 8 -g prodigal-gv -o phageX_pharokka_gv
```

**Comment by raw937** [comment]
Same error when I tried to install base mash from conda. 
Traceback (most recent call last):
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 489, in <module>
    main()
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 128, in main
    ) = check_dependencies(args.skip_mash)
  File "/home/docwhite/miniconda3/envs/pharokka/bin/input_commands.py", line 540, in check_dependencies
    mash_major_version = int(mash_out.split(".")[0])
ValueError: invalid literal for int() with base 10: 'mash: error while loading shared libraries: libgsl'

This fixed it:
```mamba install mash=2.2```

All fixed and running again. 

I would save this for others. Unsure it's a mash 2.3 or 2.1 issue. But, 2.2 works.
