### ISSUE TITLE
Issues with pharokka_multiplotter.py 

### ISSUE THREAD

**Issue by aryehjc** [gbouras13/pharokka#348]
* pharokka version: 1.7.2
* Python version: 3.10.12
* Operating System: Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### Description

Hello,
I was running pharokka_multiplotter.py on a contigs.fasta file with 55 contigs, and the command crashed with the following output below.
Please help thank you

### What I Did

/home/aryeh/pharokka-1.7.2/bin/./pharokka_multiplotter.py -g pharokka.gbk -o pharokka_plots_output_directory
2024-06-24 13:20:32.493 | INFO     | __main__:<module>:103 - Starting Pharokka v1.7.2
2024-06-24 13:20:32.493 | INFO     | __main__:<module>:104 - Running pharokka_multiplotter.py to plot your phages.
2024-06-24 13:20:32.493 | INFO     | __main__:<module>:105 - Command executed: Namespace(genbank='pharokka.gbk', outdir='pharokka_plots_output_directory', force=False, label_hypotheticals=False, remove_other_features_labels=False, title_size='20', label_size='8', interval='5000', truncate='20', dpi='600', annotations='1', plot_title='Phage', label_ids='')
2024-06-24 13:20:32.493 | INFO     | __main__:<module>:106 - Repository homepage is https://github.com/gbouras13/pharokka
2024-06-24 13:20:32.493 | INFO     | __main__:<module>:107 - Written by George Bouras: george.bouras@adelaide.edu.au
2024-06-24 13:20:32.493 | INFO     | __main__:<module>:108 - Checking your inputs.
2024-06-24 13:20:32.493 | INFO     | __main__:<module>:194 - All files checked.
2024-06-24 13:20:32.674 | INFO     | __main__:<module>:244 - Plotting contig_1
... (continued after a few contigs) ...
/home/aryeh/.local/lib/python3.10/site-packages/pycirclize/circos.py:888: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig = plt.figure(figsize=figsize, dpi=dpi, tight_layout=True)
... (continued after a few contigs) ...
Traceback (most recent call last):
  File "/home/aryeh/pharokka-1.7.2/bin/./pharokka_multiplotter.py", line 246, in <module>
    create_single_plot(
  File "/home/aryeh/pharokka-1.7.2/bin/plot.py", line 970, in create_single_plot
    quantile_length = np.quantile(length_list, annotations)
  File "/home/aryeh/.local/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4543, in quantile
    return _quantile_unchecked(
  File "/home/aryeh/.local/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4555, in _quantile_unchecked
    return _ureduce(a,
  File "/home/aryeh/.local/lib/python3.10/site-packages/numpy/lib/function_base.py", line 3823, in _ureduce
    r = func(a, **kwargs)
  File "/home/aryeh/.local/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4721, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/home/aryeh/.local/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4830, in _quantile
    slices_having_nans = np.isnan(arr[-1, ...])
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by gbouras13** [comment]
Hi @aryehjc ,

Have you tried plotting contig_31 with the regular pharokka plot function? I suspect that it may just have no CDS (and so a plot would be a bit useless :) ). Alternatively, please upload it and I will try and replicate it.

George

**Comment by mawulin** [comment]
Solution: Fixing Empty Array Error in Pharokka Plotter

Problem Analysis

The error occurs in plot.py at line 970 when np.quantile(length_list, annotations) is called on an empty length_list array. This happens when:

• Input sequences contain no CDS features to annotate

• All CDS features are filtered out (e.g., when hypothetical proteins are excluded and all proteins are hypothetical)

• GenBank file contains sequences with no annotated features

Required Code Modifications

Modification 1: create_single_plot function (around line 970)

Original Code:
    ####### running the sparsity

    quantile_length = np.quantile(length_list, annotations)
    # Create an empty list to store the filtered indices
    filtered_indices = []

    # Loop through the indices of the length_list
    for i in range(len(length_list)):
        # If the length at this index is greater than or equal to the median, add the index to filtered_indices
        # captures the once in the label force list
        if (length_list[i] < quantile_length) or (id_list[i] in label_force_list):
            filtered_indices.append(i)


Fixed Code:
    ####### running the sparsity

    # FIX: Add empty array check
    if len(length_list) == 0:
        logger.warning(f"Contig {contig_id} has no CDS features to annotate. Skipping annotation filtering.")
        # Set empty filtered indices to skip annotation steps
        filtered_indices = []
    else:
        quantile_length = np.quantile(length_list, annotations)
        # Create an empty list to store the filtered indices
        filtered_indices = []

        # Loop through the indices of the length_list
        for i in range(len(length_list)):
            # If the length at this index is greater than or equal to the median, add the index to filtered_indices
            # captures the once in the label force list
            if (length_list[i] < quantile_length) or (id_list[i] in label_force_list):
                filtered_indices.append(i)


Modification 2: create_plot function (around line 466)

Original Code:
    ####### running the sparsity

    quantile_length = np.quantile(length_list, annotations)
    # Create an empty list to store the filtered indices
    filtered_indices = []

    # Loop through the indices of the length_list
    for i in range(len(length_list)):
        # If the length at this index is greater than or equal to the median, add the index to filtered_indices
        # captures the once in the label force list
        if (length_list[i] < quantile_length) or (id_list[i] in label_force_list):
            filtered_indices.append(i)


Fixed Code:
    ####### running the sparsity

    # FIX: Add empty array check
    if len(length_list) == 0:
        logger.warning("No CDS features to annotate. Skipping annotation filtering.")
        filtered_indices = []
    else:
        quantile_length = np.quantile(length_list, annotations)
        # Create an empty list to store the filtered indices
        filtered_indices = []

        # Loop through the indices of the length_list
        for i in range(len(length_list)):
            # If the length at this index is greater than or equal to the median, add the index to filtered_indices
            # captures the once in the label force list
            if (length_list[i] < quantile_length) or (id_list[i] in label_force_list):
                filtered_indices.append(i)


Key Changes Made

1. Empty Array Check: Added if len(length_list) == 0: before calling np.quantile()
2. Warning Logging: Added informative warning messages when no CDS features are found
3. Graceful Degradation: When array is empty, set filtered_indices = [] to continue plotting without annotations
4. Preserved Logic: Maintained all original functionality, only added error handling

Benefits of This Fix

• Prevents Runtime Errors: Avoids IndexError: index -1 is out of bounds for axis 0 with size 0

• Better User Experience: Provides clear warning messages about empty sequences

• Continued Operation: Allows the script to generate genome maps even for sequences with no CDS features

• Backward Compatibility: No changes to existing functionality or output format

Testing Recommendations

After applying the fix, test with:
1. Normal GenBank files with CDS features
2. GenBank files containing sequences with no CDS features
3. Mixed files containing both annotated and unannotated sequences

**Comment by gbouras13** [comment]
Hi @mawulin  - please make a PR if you'd like credit for this, otherwise I will add myself in the next version - thanks for the fix!

George
