### ISSUE TITLE
Inquiry on error for running protein annotation 

### ISSUE THREAD

**Issue by songmj86** [gbouras13/pharokka#354]
* pharokka version: 1.7.3
* Python version: 3.10.14
* Operating System: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-101-generic x86_64)

### Description
Hi. I am tyring to annotate the viral protein using following commands & the run was halted with the following error

Could you help me resolve this issue?

Thanks !

### What I Did
# Instllation command
conda create -y -c conda-forge -c bioconda -n Pharokka pharokka=1.7.3 ;
conda activate Pharokka ;

# Run command 
conda activate Pharokka ; 
DB="/home/pharokka_v1.4.0_databases" ; 
In="/home/Protein.faa" ; 
Out="/home/Pharokka_Test" ; 
pharokka_proteins.py -d $DB -t 100 -i $In -o $Out ;
conda deactivate ; 

# Output error
2024-07-15 22:16:39.315 | INFO     | __main__:main:64 - Starting Pharokka v1.7.3
2024-07-15 22:16:39.317 | INFO     | __main__:main:65 - Running pharokka_proteins.py to annotate proteins.
2024-07-15 22:16:39.317 | INFO     | __main__:main:66 - Command executed: Namespace(infile='Protein.faa', outdir='/home/Pharokka_Test', database='/home/pharokka_v1.4.0_databases', threads='80', force=False, prefix='Default', evalue='1E-05', hmm_only=False, mmseqs2_only=False, citation=False)
2024-07-15 22:16:39.317 | INFO     | __main__:main:67 - Repository homepage is https://github.com/gbouras13/pharokka
2024-07-15 22:16:39.317 | INFO     | __main__:main:68 - Written by George Bouras: george.bouras@adelaide.edu.au
2024-07-15 22:16:39.317 | INFO     | __main__:main:71 - Checking database installation.
2024-07-15 22:16:39.317 | INFO     | __main__:main:75 - All databases have been successfully checked.
2024-07-15 22:16:39.317 | INFO     | __main__:main:82 - Checking dependencies.
2024-07-15 22:16:39.462 | INFO     | input_commands:check_dependencies:383 - Phanotate version found is v1.5.1
2024-07-15 22:16:39.462 | INFO     | input_commands:check_dependencies:392 - Phanotate version is ok.
2024-07-15 22:16:39.465 | INFO     | input_commands:check_dependencies:414 - MMseqs2 version found is v13.45111
2024-07-15 22:16:39.465 | INFO     | input_commands:check_dependencies:423 - MMseqs2 version is ok.
2024-07-15 22:16:39.533 | INFO     | input_commands:check_dependencies:447 - tRNAscan-SE version found is v2.0.12
2024-07-15 22:16:39.534 | INFO     | input_commands:check_dependencies:458 - tRNAscan-SE version is ok.
2024-07-15 22:16:39.597 | INFO     | input_commands:check_dependencies:482 - MinCED version found is v0.4.2
2024-07-15 22:16:39.598 | INFO     | input_commands:check_dependencies:493 - MinCED version is ok.
2024-07-15 22:16:39.603 | INFO     | input_commands:check_dependencies:519 - ARAGORN version found is v1.2.41
2024-07-15 22:16:39.604 | INFO     | input_commands:check_dependencies:530 - ARAGORN version is ok.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/Pharokka/bin/pharokka_proteins.py", line 213, in <module>
    main()
  File "/opt/anaconda3/envs/Pharokka/bin/pharokka_proteins.py", line 83, in main
    check_dependencies(False)  # to check pharokka_proteins.py, don't need mash
  File "/opt/anaconda3/envs/Pharokka/bin/input_commands.py", line 544, in check_dependencies
    mash_major_version = int(mash_out.split(".")[0])
ValueError: invalid literal for int() with base 10: 'mash: error while loading shared libraries: libgsl'

**Comment by gbouras13** [comment]
Hi @songmj86 

mash didnt install properly. Try mash v 2.2

try running

conda install mash==2.2

george

**Comment by songmj86** [comment]
Super fast response

Thanks!
