### ISSUE TITLE
mmseqs minor version

### ISSUE THREAD

**Issue by Mewgia** [gbouras13/pharokka#356]
* pharokka version 1.7.3
* Python version 3.9.16
* Operating System debian 11

### Description

Dear George,
i have an issue with mmseqs:
pharokka.py \
-i /home/yana/download/Escherichia_phage_Pu.fasta \
-o /home/yana/download/annotation/Pu --force \
-d /home/yana/download/pharokka/ \
-g prodigal \
-t 8
(with --fast or without, result is the same)
2024-08-20 10:23:50.474 | INFO     | input_commands:instantiate_dirs:183 - Removing output directory /home/yana/download/annotation/Pu as -f or --force was specified.
2024-08-20 10:23:50.491 | INFO     | __main__:main:95 - Starting Pharokka v1.7.3
2024-08-20 10:23:50.492 | INFO     | __main__:main:96 - Command executed: Namespace(infile='/home/yana/download/Escherichia_phage_Pu.fasta', outdir='/home/yana/download/annotation/Pu', database='/home/yana/download/pharokka/', threads='8', force=True, prefix='Default', locustag='Default', gene_predictor='prodigal', meta=False, split=False, coding_table='11', evalue='1E-05', fast=True, mmseqs2_only=False, meta_hmm=False, dnaapler=False, custom_hmm='', genbank=False, terminase=False, terminase_strand='nothing', terminase_start='nothing', skip_extra_annotations=False, skip_mash=False, minced_args='', mash_distance=0.2, citation=False)
2024-08-20 10:23:50.492 | INFO     | __main__:main:97 - Repository homepage is https://github.com/gbouras13/pharokka
2024-08-20 10:23:50.493 | INFO     | __main__:main:98 - Written by George Bouras: george.bouras@adelaide.edu.au
2024-08-20 10:23:50.494 | INFO     | __main__:main:100 - Checking database installation in /home/yana/download/pharokka/.
2024-08-20 10:23:50.495 | INFO     | __main__:main:103 - All databases have been successfully checked.
2024-08-20 10:23:50.495 | INFO     | __main__:main:119 - Checking dependencies.
2024-08-20 10:23:50.850 | INFO     | input_commands:check_dependencies:383 - Phanotate version found is v1.6.5
2024-08-20 10:23:50.851 | INFO     | input_commands:check_dependencies:392 - Phanotate version is ok.
Traceback (most recent call last):
  File "/home/yana/.pyenv/versions/3.9.16/bin/pharokka.py", line 4, in <module>
    __import__('pkg_resources').run_script('Pharokka==1.7.3', 'pharokka.py')
  File "/home/yana/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/yana/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/yana/.pyenv/versions/3.9.16/lib/python3.9/site-packages/Pharokka-1.7.3-py3.9.egg/EGG-INFO/scripts/pharokka.py", line 489, in <module>
    main()
  File "/home/yana/.pyenv/versions/3.9.16/lib/python3.9/site-packages/Pharokka-1.7.3-py3.9.egg/EGG-INFO/scripts/pharokka.py", line 128, in main
    ) = check_dependencies(args.skip_mash)
  File "/home/yana/.pyenv/versions/3.9.16/lib/python3.9/site-packages/Pharokka-1.7.3-py3.9.egg/EGG-INFO/scripts/input_commands.py", line 412, in check_dependencies
    mmseqs_minor_version = int(mmseqs_version.split(".")[1])
ValueError: invalid literal for int() with base 10: '6f452'

hope for your help, i'm new in phage annotation.
Thanks a lot in advance.

**Comment by gbouras13** [comment]
Hi @Mewgia 

I think you have mmseqs v 15.6f452 installed. Pharokka needs `mmseqs2==13.45111` installed.

It looks like you aren't using conda/mamba, so please try installing that version however you have installed mmseqs.

George

**Comment by Mewgia** [comment]
Yes, it works perfectly. Thanks for such a useful tool.

**Comment by gbouras13** [comment]
Hi @Mewgia,

I think it is because a gene is too small (or full or Ns) - so that pyhmmer can't figure out if it is nucleotide or protein.

I'd check 'phanotate_aas_tmp.fasta' - it likely has a gene that is NNNNN or something. It suggests phanotate is probably not a great model for this phage, so I'd use the prodigal gene calls.

George
