### ISSUE TITLE
fails at pyhmmer

### ISSUE THREAD

**Issue by dcampbdc** [gbouras13/pharokka#357]
* pharokka version: 1.6.1
* Python version: 3.12.2
* Operating System: Linux Mint 21.3

Hi! I'm trying to run pharokka.py on a contig and it always gets stuck in the same place after starting to run pyhmmer. None of my other contigs from the dataset return this error.

$ pharokka.py -t 2 -d ~/pharokka_DB/ --skip_mash -i 8p5_11B_NODE_62_length_2252_cov_44.925878.fna -o 8p5_11B_NODE_62_length_2252_cov_44.925878_pharokka -f

Traceback (most recent call last):
  File "/home/ddawg/miniconda/bin/pharokka.py", line 499, in <module>
    main()
  File "/home/ddawg/miniconda/bin/pharokka.py", line 364, in main
    best_results_pyhmmer = run_pyhmmer(
                           ^^^^^^^^^^^^
  File "/home/ddawg/miniconda/bin/hmm.py", line 34, in run_pyhmmer
    with pyhmmer.easel.SequenceFile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyhmmer/easel.pyx", line 6289, in pyhmmer.easel.SequenceFile.__init__
  File "pyhmmer/easel.pyx", line 6283, in pyhmmer.easel.SequenceFile.__init__
ValueError: Could not determine alphabet of file: '8p5_11B_NODE_62_length_2252_cov_44.925878_pharokka/phanotate_aas_tmp.fasta'

Input fasta: [8p5_11B_NODE_62_length_2252_cov_44.925878.fna.txt](https://github.com/user-attachments/files/16698755/8p5_11B_NODE_62_length_2252_cov_44.925878.fna.txt)

**Comment by Fazel-AVB** [comment]
Hi, did you come up with a solution for this error? I am facing the exact same thing.
