### ISSUE TITLE
Unexpected failure on cluster installation and Galaxy issue

### ISSUE THREAD

**Issue by mafene00** [gbouras13/pharokka#362]
* pharokka version:1.7.3
* Python version:3.10.14
* Operating System: Linux
(on the cluster)
* pharokka version:1.3.2
* Python version: unsure
* Operating System: Linux (I suppose)

### Description

I was trying to annotate a regular phage genome and failed to do so. I recently reinstalled pharokka on the university cluster, so suspecting an issue with the installation I tried to annotate with pharokka on Galaxy ( toolshed.g2.bx.psu.edu/repos/iuc/pharokka/pharokka/1.3.2+galaxy0. ) but got the same error. 

### What I Did

```
Cluster:

conda activate pharokkaENV 
pharokka.py -i "/cluster/home/emaffei/Pharokka/Inputs/Pseudomonas_virus_PB1vMPHB.fasta" -o "/cluster/home/emaffei/Pharokka/Outputs/PB1" -d "/cluster/home/emaffei/miniconda3/envs/pharokkaENV/databases/" -t 24 -p "PB1" -f

Traceback (most recent call last):
  File "/cluster/home/emaffei/miniconda3/envs/pharokkaENV/bin/pharokka.py", line 489, in <module>
    main()
  File "/cluster/home/emaffei/miniconda3/envs/pharokkaENV/bin/pharokka.py", line 403, in main
    pharok.process_results()
  File "/cluster/home/emaffei/miniconda3/envs/pharokkaENV/bin/post_processing.py", line 261, in process_results
    merged_df[["mmseqs_phrog", "mmseqs_top_hit"]] = merged_df[
  File "/cluster/home/emaffei/miniconda3/envs/pharokkaENV/lib/python3.10/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/cluster/home/emaffei/miniconda3/envs/pharokkaENV/lib/python3.10/site-packages/pandas/core/frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/cluster/home/emaffei/miniconda3/envs/pharokkaENV/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key


Galaxy: 
pharokka.py -i '/data/dnb10/galaxy_db/files/c/f/e/dataset_cfefebf8-8311-4188-87bc-c19e63f6714e.dat' -o pharokka_output -d '/data/db/data_managers/pharokka_database/db_from_2023-08-27T050123Z' -t ${GALAXY_SLOTS:-8} -g phanotate  -e '1e-05'

Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/mulled-v1-d4c42170c031fecaaeb1602ebaa1e79ddc53efea33052033eb6358c414db352c/bin/pharokka.py", line 174, in <module>
    (cds_mmseqs_merge_df, vfdb_results, card_results) = post_processing.process_results(db_dir, out_dir, prefix, gene_predictor)
  File "/usr/local/tools/_conda/envs/mulled-v1-d4c42170c031fecaaeb1602ebaa1e79ddc53efea33052033eb6358c414db352c/bin/post_processing.py", line 68, in process_results
    merged_df[['phrog','top_hit']] = merged_df['phrog'].str.split(' ## ',expand=True)
  File "/usr/local/tools/_conda/envs/mulled-v1-d4c42170c031fecaaeb1602ebaa1e79ddc53efea33052033eb6358c414db352c/lib/python3.10/site-packages/pandas/core/frame.py", line 3938, in __setitem__
    self._setitem_array(key, value)
  File "/usr/local/tools/_conda/envs/mulled-v1-d4c42170c031fecaaeb1602ebaa1e79ddc53efea33052033eb6358c414db352c/lib/python3.10/site-packages/pandas/core/frame.py", line 3980, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/usr/local/tools/_conda/envs/mulled-v1-d4c42170c031fecaaeb1602ebaa1e79ddc53efea33052033eb6358c414db352c/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 392, in check_key_length
    raise ValueError("Columns must be same length as key")


Maybe the issue is trivial but the fact that I got the same error from independent installations prompted me to open one here.

Thank you in advance,

Enea

**Comment by gbouras13** [comment]
Hi @mafene00 ,

This is definitely a bug with pharokka - do you mind sharing the input FASTA so I can troubleshoot? My guess is Pharokka found no hits.

George

**Comment by mafene00** [comment]
Hi George,

thanks for the very fast reply! I’m sending you the FASTA file attached.


Kind regards,

Enea

Enea Maffei | Post-doctoral Researcher | ETH Zurich | Institute of Food, Nutrition and Health | Schmelzbergstrasse 7, LFV B32.1 | CH-8092 Zürich

**Comment by mafene00** [comment]
Here the file: 
[Pseudomonas_virus_PB1vMPHB.txt](https://github.com/user-attachments/files/17278311/Pseudomonas_virus_PB1vMPHB.txt)

**Comment by gbouras13** [comment]
Very strange - it works for me, so not sure it is a bug with pharokka... But weird it fails Galaxy and your cluster so not really sure is going on.

[Pseudomonas_virus_PB1vMPHB_out.tar.gz](https://github.com/user-attachments/files/17278495/Pseudomonas_virus_PB1vMPHB_out.tar.gz)

I've attached the output run with this command

```
pharokka.py -i Pseudomonas_virus_PB1vMPHB.txt -o Pseudomonas_virus_PB1vMPHB_out -t 8 -d pharokka_db -f -p "PB1"
```

It was done with v1.7.4-dev, which is identical to v1.7.3 for that command above.

George

**Comment by mafene00** [comment]
Now it's working for me too... Very strange. I apologize for the inconvenience and thank you very much for helping out and for creating and maintaining this great tool (and phold!)

**Comment by gbouras13** [comment]
Thanks for the kind words and no problems @mafene00 - closing this issue now
