### ISSUE TITLE
Error while running pharokka

### ISSUE THREAD

**Issue by GM110Z** [gbouras13/pharokka#363]
* pharokka version:
* Python version:3.9
* Operating System:MacOs osx-arm64 

### Description

Hello
I have installed pharokka through pip.  However, it always gets stuck to an error that mentiones mmseqs and mash sketch, so i am not sure what is wrong. I have run the below
 pharokka.py -i NZ_CAMITL010000003.1_157677_163122.fasta --force -d /Users/miniconda3/bin/../databases/

```
What i get is the below:

2024-10-18 07:55:53.926 | INFO     | input_commands:instantiate_dirs:183 - Removing output directory /Users/giusym/Desktop/Serratiaprojects/prophages-workdir/p2hots/output/ as -f or --force was specified.
2024-10-18 07:55:53.931 | INFO     | __main__:main:95 - Starting Pharokka v1.7.3
2024-10-18 07:55:53.931 | INFO     | __main__:main:96 - Command executed: Namespace(infile='NZ_CAMITL010000003.1_157677_163122.fasta', outdir='/Users/giusym/Desktop/Serratiaprojects/prophages-workdir/p2hots/output/', database='/Users/giusym/miniconda3/bin/../databases/', threads='1', force=True, prefix='Default', locustag='Default', gene_predictor='default', meta=False, split=False, coding_table='11', evalue='1E-05', fast=False, mmseqs2_only=False, meta_hmm=False, dnaapler=False, custom_hmm='', genbank=False, terminase=False, terminase_strand='nothing', terminase_start='nothing', skip_extra_annotations=False, skip_mash=False, minced_args='', mash_distance=0.2, citation=False)
2024-10-18 07:55:53.931 | INFO     | __main__:main:97 - Repository homepage is https://github.com/gbouras13/pharokka
2024-10-18 07:55:53.931 | INFO     | __main__:main:98 - Written by George Bouras: george.bouras@adelaide.edu.au
2024-10-18 07:55:53.931 | INFO     | __main__:main:100 - Checking database installation in /Users/giusym/miniconda3/bin/../databases/.
2024-10-18 07:55:53.932 | INFO     | __main__:main:103 - All databases have been successfully checked.
2024-10-18 07:55:53.932 | INFO     | __main__:main:119 - Checking dependencies.
2024-10-18 07:55:54.149 | INFO     | input_commands:check_dependencies:383 - Phanotate version found is v1.6.5
2024-10-18 07:55:54.149 | INFO     | input_commands:check_dependencies:392 - Phanotate version is ok.
Traceback (most recent call last):
  File "/Users/giusym/miniconda3/bin/pharokka.py", line 489, in <module>
    main()
  File "/Users/giusym/miniconda3/bin/pharokka.py", line 128, in main
    ) = check_dependencies(args.skip_mash)
  File "/Users/giusym/miniconda3/bin/input_commands.py", line 411, in check_dependencies
    mmseqs_major_version = int(mmseqs_version.split(".")[0])
ValueError: invalid literal for int() with base 10: '15-6f452'
```
I have Mmseq2 installed in the same environmen and it works as standalone. Same for mash.

**Comment by gbouras13** [comment]
Hi @GM110Z 

mmseqs needs to be v13.45111 - so try installing that version, should make the error disappear.

george
