### ISSUE TITLE
Problem or bug with dnaapler

### ISSUE THREAD

**Issue by reynaldoponcealmeri** [gbouras13/pharokka#368]
* pharokka version: pharokka-1.7.3
* Python version: 3.11.5
* Operating System: MaCOS

### Description
the programm is getting stuck with the following message: dnaapler deprecated
### What I Did

```
reynaldoponcealmeri@Mac ~ % pharokka.py -i NB0521_09R.fasta -o NB0521_09R -d ~/miniconda3/databases
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
2024-11-17 21:25:50.114 | INFO     | __main__:main:95 - Starting Pharokka v1.7.3
2024-11-17 21:25:50.114 | INFO     | __main__:main:96 - Command executed: Namespace(infile='NB0521_09R.fasta', outdir='NB0521_09R', database='/Users/reynaldoponcealmeri/miniconda3/databases', threads='1', force=False, prefix='Default', locustag='Default', gene_predictor='default', meta=False, split=False, coding_table='11', evalue='1E-05', fast=False, mmseqs2_only=False, meta_hmm=False, dnaapler=False, custom_hmm='', genbank=False, terminase=False, terminase_strand='nothing', terminase_start='nothing', skip_extra_annotations=False, skip_mash=False, minced_args='', mash_distance=0.2, citation=False)
2024-11-17 21:25:50.115 | INFO     | __main__:main:97 - Repository homepage is https://github.com/gbouras13/pharokka
2024-11-17 21:25:50.115 | INFO     | __main__:main:98 - Written by George Bouras: george.bouras@adelaide.edu.au
2024-11-17 21:25:50.115 | INFO     | __main__:main:100 - Checking database installation in /Users/reynaldoponcealmeri/miniconda3/databases.
2024-11-17 21:25:50.115 | INFO     | __main__:main:103 - All databases have been successfully checked.
2024-11-17 21:25:50.115 | INFO     | __main__:main:119 - Checking dependencies.
2024-11-17 21:25:50.250 | INFO     | input_commands:check_dependencies:383 - Phanotate version found is v1.6.6
2024-11-17 21:25:50.251 | INFO     | input_commands:check_dependencies:392 - Phanotate version is ok.
2024-11-17 21:25:50.281 | INFO     | input_commands:check_dependencies:414 - MMseqs2 version found is v13.45111
2024-11-17 21:25:50.281 | INFO     | input_commands:check_dependencies:423 - MMseqs2 version is ok.
2024-11-17 21:25:50.370 | INFO     | input_commands:check_dependencies:447 - tRNAscan-SE version found is v2.0.12
2024-11-17 21:25:50.371 | INFO     | input_commands:check_dependencies:458 - tRNAscan-SE version is ok.
2024-11-17 21:25:50.621 | INFO     | input_commands:check_dependencies:482 - MinCED version found is v0.4.2
2024-11-17 21:25:50.622 | INFO     | input_commands:check_dependencies:493 - MinCED version is ok.
2024-11-17 21:25:50.643 | INFO     | input_commands:check_dependencies:519 - ARAGORN version found is v1.2.41
2024-11-17 21:25:50.643 | INFO     | input_commands:check_dependencies:530 - ARAGORN version is ok.
2024-11-17 21:25:50.668 | INFO     | input_commands:check_dependencies:547 - mash version found is v2.3
2024-11-17 21:25:50.668 | INFO     | input_commands:check_dependencies:554 - mash version is ok.
Traceback (most recent call last):
  File "/Users/reynaldoponcealmeri/miniconda3/bin/pharokka.py", line 489, in <module>
    main()
  File "/Users/reynaldoponcealmeri/miniconda3/bin/pharokka.py", line 128, in main
    ) = check_dependencies(args.skip_mash)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reynaldoponcealmeri/miniconda3/bin/input_commands.py", line 569, in check_dependencies
    dnaapler_major_version = int(dnaapler_out.split(".")[0])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'deprecated'

```
THANKS IN ADVANCE FOR YOUR HELP

**Comment by gbouras13** [comment]
Hi @reynaldoponcealmeri ,

I am quite sure this is an issue with Macs and BLAST (a dependency of Dnaapler) - I assume you have an M series chip. How did you install pharokka? Conda?

If you don't require dnaapler, you could also simply comment out line 569 in `/Users/reynaldoponcealmeri/miniconda3/bin/input_commands.py` as a quick fix.

There are 2 full solution options if you use conda:

1. Install the x86_64 version of miniforge

```
https://github.com/conda-forge/miniforge
```

* In practice, many well known bioinformatics programs (beyond BLAST) don't work with M1 yet, so by installing the x86_64 version, Rosetta will run under the hood.

2.

You can try

```
conda create --subdir osx-64 --name pharokka pharokka
```

which should work too

George

**Comment by gbouras13** [comment]
Hi @reynaldoponcealmeri - please try `v1.7.4` with the updated documentation in the `README.md` for MacOS Apple Silicon environments.

George
