### ISSUE TITLE
Error in post_processing

### ISSUE THREAD

**Issue by pmaen** [gbouras13/pharokka#371]
* pharokka version: 1.7.4
* Python version: 3.10.14
* Operating System: Ubuntu 24.04 LTS

### Description

When running Pharokka on a single phage genome I get the following error:

### What I Did

```
pharokka.py -i jg004.fasta -o pharokka_jg004 -t 7 -d /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/
2024-11-28 13:34:39.366 | INFO     | __main__:main:95 - Starting Pharokka v1.7.4
2024-11-28 13:34:39.367 | INFO     | __main__:main:96 - Command executed: Namespace(infile='jg004.fasta', outdir='pharokka_jg004', database='/home/paul/anaconda3/envs/pharokkaENV/bin/../databases/', threads='7', force=False, prefix='Default', locustag='Default', gene_predictor='default', meta=False, split=False, coding_table='11', evalue='1E-05', fast=False, mmseqs2_only=False, meta_hmm=False, dnaapler=False, custom_hmm='', genbank=False, terminase=False, terminase_strand='nothing', terminase_start='nothing', skip_extra_annotations=False, skip_mash=False, minced_args='', mash_distance=0.2, trna_scan_model='general', citation=False)
2024-11-28 13:34:39.367 | INFO     | __main__:main:97 - Repository homepage is https://github.com/gbouras13/pharokka
2024-11-28 13:34:39.367 | INFO     | __main__:main:98 - Written by George Bouras: george.bouras@adelaide.edu.au
2024-11-28 13:34:39.367 | INFO     | __main__:main:100 - Checking database installation in /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/.
2024-11-28 13:34:39.367 | INFO     | __main__:main:103 - All databases have been successfully checked.
2024-11-28 13:34:39.368 | INFO     | __main__:main:119 - Checking dependencies.
2024-11-28 13:34:39.513 | INFO     | input_commands:check_dependencies:390 - Phanotate version found is v1.5.1
2024-11-28 13:34:39.513 | INFO     | input_commands:check_dependencies:399 - Phanotate version is ok.
2024-11-28 13:34:39.516 | INFO     | input_commands:check_dependencies:426 - MMseqs2 version found is v13.45111
2024-11-28 13:34:39.516 | INFO     | input_commands:check_dependencies:435 - MMseqs2 version is ok.
2024-11-28 13:34:39.589 | INFO     | input_commands:check_dependencies:459 - tRNAscan-SE version found is v2.0.12
2024-11-28 13:34:39.589 | INFO     | input_commands:check_dependencies:470 - tRNAscan-SE version is ok.
2024-11-28 13:34:39.634 | INFO     | input_commands:check_dependencies:494 - MinCED version found is v0.4.2
2024-11-28 13:34:39.635 | INFO     | input_commands:check_dependencies:505 - MinCED version is ok.
2024-11-28 13:34:39.636 | INFO     | input_commands:check_dependencies:531 - ARAGORN version found is v1.2.41
2024-11-28 13:34:39.636 | INFO     | input_commands:check_dependencies:542 - ARAGORN version is ok.
2024-11-28 13:34:39.641 | INFO     | input_commands:check_dependencies:559 - mash version found is v2.3
2024-11-28 13:34:39.641 | INFO     | input_commands:check_dependencies:566 - mash version is ok.
2024-11-28 13:34:40.369 | INFO     | input_commands:check_dependencies:585 - Dnaapler version found is v1.0.1
2024-11-28 13:34:40.369 | INFO     | input_commands:check_dependencies:592 - Dnaapler version is ok.
2024-11-28 13:34:40.369 | INFO     | input_commands:check_dependencies:604 - Pyrodigal version is v3.6.3
2024-11-28 13:34:40.370 | INFO     | input_commands:check_dependencies:605 - Pyrodigal version is ok.
2024-11-28 13:34:40.370 | INFO     | input_commands:check_dependencies:617 - Pyrodigal_gv version is v0.3.2
2024-11-28 13:34:40.370 | INFO     | input_commands:check_dependencies:618 - Pyrodigal_gv version is ok.
2024-11-28 13:34:40.375 | INFO     | input_commands:validate_fasta:237 - Checking input jg004.fasta.
2024-11-28 13:34:40.375 | INFO     | input_commands:validate_fasta:239 - Input jg004.fasta is in FASTA format.
2024-11-28 13:34:40.375 | INFO     | input_commands:validate_fasta:244 - Checking input jg004.fasta for duplicate FASTA headers.
2024-11-28 13:34:40.376 | INFO     | input_commands:validate_fasta:246 - All headers in jg004.fasta are unique.
2024-11-28 13:34:40.376 | INFO     | input_commands:validate_gene_predictor:275 - Phanotate will be used for gene prediction.
2024-11-28 13:34:40.376 | INFO     | __main__:main:280 - Running Phanotate.
2024-11-28 13:34:40.377 | INFO     | external_tools:run:50 - Started running phanotate.py -f fasta -o pharokka_jg004/phanotate_out_tmp.fasta jg004.fasta ...
2024-11-28 13:35:03.459 | INFO     | external_tools:run:52 - Done running phanotate.py -f fasta -o pharokka_jg004/phanotate_out_tmp.fasta jg004.fasta
2024-11-28 13:35:03.459 | INFO     | external_tools:run:50 - Started running phanotate.py -f tabular -o pharokka_jg004/phanotate_out.txt jg004.fasta ...
2024-11-28 13:35:25.007 | INFO     | external_tools:run:52 - Done running phanotate.py -f tabular -o pharokka_jg004/phanotate_out.txt jg004.fasta
2024-11-28 13:35:25.061 | INFO     | __main__:main:309 - Starting tRNA-scanSE.
2024-11-28 13:35:25.062 | INFO     | external_tools:run:50 - Started running tRNAscan-SE --thread 7 -G -Q -j pharokka_jg004/trnascan_out.gff jg004.fasta ...
2024-11-28 13:35:27.101 | INFO     | external_tools:run:52 - Done running tRNAscan-SE --thread 7 -G -Q -j pharokka_jg004/trnascan_out.gff jg004.fasta
2024-11-28 13:35:27.102 | INFO     | processes:run_minced:832 - Running MinCED.
2024-11-28 13:35:27.102 | INFO     | external_tools:run:50 - Started running minced jg004.fasta pharokka_jg004/pharokka_minced_spacers.txt pharokka_jg004/pharokka_minced.gff ...
2024-11-28 13:35:27.207 | INFO     | external_tools:run:52 - Done running minced jg004.fasta pharokka_jg004/pharokka_minced_spacers.txt pharokka_jg004/pharokka_minced.gff
2024-11-28 13:35:27.208 | INFO     | processes:run_aragorn:864 - Running Aragorn.
2024-11-28 13:35:27.208 | INFO     | external_tools:run:50 - Started running aragorn -l -gcbact -w -m -o pharokka_jg004/pharokka_aragorn.txt jg004.fasta ...
2024-11-28 13:35:27.231 | INFO     | external_tools:run:52 - Done running aragorn -l -gcbact -w -m -o pharokka_jg004/pharokka_aragorn.txt jg004.fasta
2024-11-28 13:35:27.232 | INFO     | __main__:main:317 - Starting MMseqs2.
2024-11-28 13:35:27.232 | INFO     | processes:run_mmseqs:685 - Running MMseqs2 on PHROG Database.
2024-11-28 13:35:27.232 | INFO     | external_tools:run:50 - Started running mmseqs createdb pharokka_jg004/phanotate_aas_tmp.fasta pharokka_jg004/target_dir/target_seqs ...
2024-11-28 13:35:27.957 | INFO     | external_tools:run:52 - Done running mmseqs createdb pharokka_jg004/phanotate_aas_tmp.fasta pharokka_jg004/target_dir/target_seqs
2024-11-28 13:35:27.957 | INFO     | external_tools:run:50 - Started running mmseqs search -e 1E-05 /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/phrogs_profile_db pharokka_jg004/target_dir/target_seqs pharokka_jg004/mmseqs/results_mmseqs pharokka_jg004/tmp_dir/ -s 8.5 --threads 7 ...
2024-11-28 13:41:13.938 | INFO     | external_tools:run:52 - Done running mmseqs search -e 1E-05 /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/phrogs_profile_db pharokka_jg004/target_dir/target_seqs pharokka_jg004/mmseqs/results_mmseqs pharokka_jg004/tmp_dir/ -s 8.5 --threads 7
2024-11-28 13:41:13.938 | INFO     | external_tools:run:50 - Started running mmseqs createtsv /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/phrogs_profile_db pharokka_jg004/target_dir/target_seqs pharokka_jg004/mmseqs/results_mmseqs pharokka_jg004/mmseqs_results.tsv --full-header --threads 7 ...
2024-11-28 13:41:13.986 | INFO     | external_tools:run:52 - Done running mmseqs createtsv /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/phrogs_profile_db pharokka_jg004/target_dir/target_seqs pharokka_jg004/mmseqs/results_mmseqs pharokka_jg004/mmseqs_results.tsv --full-header --threads 7
2024-11-28 13:41:13.986 | INFO     | processes:run_mmseqs:685 - Running MMseqs2 on CARD Database.
2024-11-28 13:41:13.987 | INFO     | external_tools:run:50 - Started running mmseqs createdb pharokka_jg004/phanotate_aas_tmp.fasta pharokka_jg004/CARD_target_dir/target_seqs ...
2024-11-28 13:41:13.998 | INFO     | external_tools:run:52 - Done running mmseqs createdb pharokka_jg004/phanotate_aas_tmp.fasta pharokka_jg004/CARD_target_dir/target_seqs
2024-11-28 13:41:13.998 | INFO     | external_tools:run:50 - Started running mmseqs search --min-seq-id 0.8 -c 0.4 /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/CARD pharokka_jg004/CARD_target_dir/target_seqs pharokka_jg004/CARD/results_mmseqs pharokka_jg004/CARD_dir/ -s 8.5 --threads 7 ...
2024-11-28 13:42:01.258 | INFO     | external_tools:run:52 - Done running mmseqs search --min-seq-id 0.8 -c 0.4 /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/CARD pharokka_jg004/CARD_target_dir/target_seqs pharokka_jg004/CARD/results_mmseqs pharokka_jg004/CARD_dir/ -s 8.5 --threads 7
2024-11-28 13:42:01.259 | INFO     | external_tools:run:50 - Started running mmseqs createtsv /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/CARD pharokka_jg004/CARD_target_dir/target_seqs pharokka_jg004/CARD/results_mmseqs pharokka_jg004/CARD_results.tsv --full-header --threads 7 ...
2024-11-28 13:42:01.273 | INFO     | external_tools:run:52 - Done running mmseqs createtsv /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/CARD pharokka_jg004/CARD_target_dir/target_seqs pharokka_jg004/CARD/results_mmseqs pharokka_jg004/CARD_results.tsv --full-header --threads 7
2024-11-28 13:42:01.274 | INFO     | processes:run_mmseqs:685 - Running MMseqs2 on VFDB Database.
2024-11-28 13:42:01.274 | INFO     | external_tools:run:50 - Started running mmseqs createdb pharokka_jg004/phanotate_aas_tmp.fasta pharokka_jg004/VFDB_target_dir/target_seqs ...
2024-11-28 13:42:01.286 | INFO     | external_tools:run:52 - Done running mmseqs createdb pharokka_jg004/phanotate_aas_tmp.fasta pharokka_jg004/VFDB_target_dir/target_seqs
2024-11-28 13:42:01.287 | INFO     | external_tools:run:50 - Started running mmseqs search --min-seq-id 0.8 -c 0.4 /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/vfdb pharokka_jg004/VFDB_target_dir/target_seqs pharokka_jg004/VFDB/results_mmseqs pharokka_jg004/VFDB_dir/ -s 8.5 --threads 7 ...
2024-11-28 13:43:21.887 | INFO     | external_tools:run:52 - Done running mmseqs search --min-seq-id 0.8 -c 0.4 /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/vfdb pharokka_jg004/VFDB_target_dir/target_seqs pharokka_jg004/VFDB/results_mmseqs pharokka_jg004/VFDB_dir/ -s 8.5 --threads 7
2024-11-28 13:43:21.888 | INFO     | external_tools:run:50 - Started running mmseqs createtsv /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/vfdb pharokka_jg004/VFDB_target_dir/target_seqs pharokka_jg004/VFDB/results_mmseqs pharokka_jg004/vfdb_results.tsv --full-header --threads 7 ...
2024-11-28 13:43:21.916 | INFO     | external_tools:run:52 - Done running mmseqs createtsv /home/paul/anaconda3/envs/pharokkaENV/bin/../databases/vfdb pharokka_jg004/VFDB_target_dir/target_seqs pharokka_jg004/VFDB/results_mmseqs pharokka_jg004/vfdb_results.tsv --full-header --threads 7
2024-11-28 13:43:21.917 | INFO     | __main__:main:348 - Running PyHMMER on PHROGs.
2024-11-28 13:43:36.228 | INFO     | __main__:main:364 - Post Processing Output.
2024-11-28 13:43:36.252 | INFO     | post_processing:create_mmseqs_tophits:2146 - Processing MMseqs2 outputs.
2024-11-28 13:43:36.252 | INFO     | post_processing:create_mmseqs_tophits:2147 - Processing PHROGs output.
2024-11-28 13:43:36.570 | INFO     | post_processing:process_vfdb_results:2351 - Processing VFDB output.
2024-11-28 13:43:36.578 | INFO     | post_processing:process_vfdb_results:2437 - 0 VFDB virulence factors identified.
2024-11-28 13:43:36.579 | INFO     | post_processing:process_card_results:2455 - Processing CARD output.
2024-11-28 13:43:36.587 | INFO     | post_processing:process_card_results:2578 - 0 CARD AMR genes identified.
2024-11-28 13:43:36.664 | INFO     | __main__:main:435 - Converting gff to genbank.
Traceback (most recent call last):
  File "/home/paul/anaconda3/envs/pharokkaENV/bin/pharokka.py", line 489, in <module>
    main()
  File "/home/paul/anaconda3/envs/pharokkaENV/bin/pharokka.py", line 437, in main
    convert_gff_to_gbk(input_fasta, out_dir, out_dir, prefix, pharok.prot_seq_df)
  File "/home/paul/anaconda3/envs/pharokkaENV/bin/processes.py", line 809, in convert_gff_to_gbk
    if feature.strand == 1:
AttributeError: 'SeqFeature' object has no attribute 'strand'
```

From what I see it has to do with the version of `biopython`. According to the conda install pharokka should be compatible with the newest biopython, however in version 1.8.2 there is no `strand` attribute anymore.

**Comment by pmaen** [comment]
#372 fixes this and removes some redundant/non-functional code

**Comment by gbouras13** [comment]
Thanks @pmaen - your PR will be part of the next release.

George
